# https://travis-ci.org/#!/translate/amagama
language: python
python:
  - 2.5
  - 2.6
  - 2.7
env:
  - REQS=/MINVERS.txt
  - REQS=.txt
  - REQS=/documentation.txt
matrix:
  exclude:
    - python: 2.5
      env: REQS=/MINVERS.txt
    - python: 2.6
      env: REQS=/MINVERS.txt
    - python: 2.6
      env: REQS=.txt
install:
  - case `python -V 2>&1` in *2.5*) pip install -r requirements/py25.txt;; esac
  - pip install -r requirements$REQS --use-mirrors
  - pip install -r requirements/documentation.txt --use-mirrors
  - pip freeze # print all installed versions for reference/posterity
before_script:
  - export PATH=`pwd`/bin:$PATH
  - export PYTHONPATH=`pwd`
  - psql -c "create database amagama with encoding 'UTF-8';" -U postgres
script:
  - cd docs && make html
  - amagama-manage initdb -s en
  - amagama-manage tmdb_stats
  - yes | amagama-manage dropdb -s en
notifications:
  email:
    on_failure: always
    on_success: change
